# This is the implicit global project's config file, which is only used
# when 'stack' is run outside of a real project.  Settings here do _not_
# act as defaults for all projects.  To change stack's default settings,
# edit '~/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
resolver: lts-17.15
packages: []

# Use compatible system-ghc over stack installed GHC when version is compatible.
system-ghc: true
ghc-options:
  $locals:
    "-j"

flags:
  xmobar:
    with_xft: true
    with_mpris: true
    with_threaded: true
    with_rtsopts: true
    with_weather: true
    #with_dbus: true

extra-deps:
  - xmobar-0.39
  - netlink-1.1.1.0 # xmobar
  - xmonad-contrib-0.17.0
  - xmonad-0.17.0
  - X11-1.10.3
