version: 2
jobs:
  build:
    working_directory: ~/dotfiles/dotfiles
    docker:
      - image: assertible/ci
    steps:
      - checkout
      - run: apt update && apt install stow -y --no-install-recommends
      - run: make dotfiles
      - run: make dotemacs
      - run: make xmonad
      - run: make theme
