version: 2
jobs:
  build:
    working_directory: ~/dotfiles/dotfiles
    docker:
      - image: archlinux:latest
    environment:
      WAYLAND_DISPLAY: wl-test-env
    steps:

      - run: pacman -Syu --noconfirm
      - run: pacman -S --noconfirm openssh git stow emacs-wayland make sudo

      - checkout

      # headless wayland for testing configs (like xvfb-run for x11)
      #
      # - run: pacman -S --noconfirm weston
      # - run: weston --no-config --socket=wl-test-env --backend=headless

      - restore_cache:
          keys:
            - v3-dotcache-{{ .Branch }}
            - v3-dotcache

      # remove pre-existing dotfiles (stow will not)
      - run: rm -f ~/.profile ~/.bashrc ~/.gitconfig && mkdir -p ~/.emacs.d
      - run: make dotfiles
      - run: make elpa
      #- run: hyprctl configerrors

      - save_cache:
          key: v3-dotcache-{{ .Branch }}
          paths:
            - ~/.stack/
            - ~/.emacs.d/elpa
