version: 2
jobs:
  build:
    working_directory: ~/dotfiles/dotfiles
    docker:
      - image: assertible/ci
    steps:
      - checkout

      - run: apt update
      - run: apt install xinit x11-xserver-utils xserver-xorg libx11-dev libxrandr-dev libxft-dev xvfb -y --no-install-recommends
      - run: apt install stow emacs -y --no-install-recommends

      - run: rm ~/.profile ~/.bashrc ~/.gitconfig
      - run: make dotfiles
      - run: xvfb-run make dotemacs
      - run: xvfb-run make theme

      - restore_cache:
          keys:
            - v1-cache-{{ .Branch }}
            - v1-cache

      - run: xvfb-run make xmonad

      - save_cache:
          key: v1-cache-{{ .Branch }}
          paths:
            - ~/.stack/

      # - run: cd $HOME && xvfb-run startx
