.pragma library

const glyphs = {
    browser: "",
    terminal: "",
    code: "",
    music: "",
    agent: "",
    window: "",
    workspaceDefault: "",
    warning: "",
    batteryCharging: "",
    batteryPlugged: "",
    batteryEmpty: "",
    batteryQuarter: "",
    batteryHalf: "",
    batteryThreeQuarters: "",
    batteryFull: "",
    brightnessMinimum: "",
    brightnessLow: "",
    brightnessLowerMiddle: "",
    brightnessMiddle: "",
    brightnessUpperMiddle: "",
    brightnessHigh: "",
    brightnessHigher: "",
    brightnessNearMaximum: "",
    brightnessMaximum: "",
    cpu: "",
    cpuLow: "󰡴",
    cpuModerate: "󰊚",
    cpuBusy: "󰓅",
    cpuHigh: "󰡳",
    memory: "",
    chip: "",
    eyeOpen: "",
    eyeClosed: "",
    bell: "",
    bellMuted: "",
    markRead: "",
    markUnread: "",
    networkConnected: "󰱔",
    networkDisconnected: "⚠",
    networkUnavailable: "󰲛",
    ethernet: "󰈀",
    wifiStrengthOutline: "󰤯",
    wifiStrength1: "󰤟",
    wifiStrength2: "󰤢",
    wifiStrength3: "󰤥",
    wifiStrength4: "󰤨",
    chevronLeft: "",
    chevronRight: "",
    upload: "",
    download: "",
    temperatureEmpty: "",
    temperatureHalf: "",
    temperatureFull: "",
    volumeOff: "",
    volumeLow: "",
    volumeMedium: "",
    volumeHigh: "",
    volumeMuted: "",
    microphone: "",
    microphoneMuted: ""
}

function glyph(name) {
    return glyphs[name] || ""
}
