.pragma library

const glyphs = {
    browser: "",
    terminal: "",
    code: "",
    music: "",
    agent: "",
    database: "",
    config: "",
    terminalWindow: "",
    windowRestore: "",
    workspaceDefault: "󱓻",
    warning: "",
    // Nerd Font md-battery_outline, md-battery_10..90, md-battery.
    batteryEmpty: "󰂎",
    batteryCapacity10: "󰁺",
    batteryCapacity20: "󰁻",
    batteryCapacity30: "󰁼",
    batteryCapacity40: "󰁽",
    batteryCapacity50: "󰁾",
    batteryCapacity60: "󰁿",
    batteryCapacity70: "󰂀",
    batteryCapacity80: "󰂁",
    batteryCapacity90: "󰂂",
    batteryFull: "󰁹",
    // md-battery_charging_outline and md-battery_charging_10..100.
    batteryChargingEmpty: "󰢟",
    batteryCharging10: "󰢜",
    batteryCharging20: "󰂆",
    batteryCharging30: "󰂇",
    batteryCharging40: "󰂈",
    batteryCharging50: "󰢝",
    batteryCharging60: "󰂉",
    batteryCharging70: "󰢞",
    batteryCharging80: "󰂊",
    batteryCharging90: "󰂋",
    batteryCharging100: "󰂅",
    // md-battery_unknown, md-battery_remove_outline, md-battery_check, md-power_plug.
    batteryUnknown: "󰂑",
    batteryAbsent: "󱟩",
    batteryFullyCharged: "󱟢",
    batteryPlugged: "󰚥",
    brightnessMinimum: "",
    brightnessLow: "",
    brightnessLowerMiddle: "",
    brightnessMiddle: "",
    brightnessUpperMiddle: "",
    brightnessHigh: "",
    brightnessHigher: "",
    brightnessNearMaximum: "",
    brightnessMaximum: "",
    cpu: "",
    cpuLow: "󰡴",
    cpuModerate: "󰊚",
    cpuBusy: "󰓅",
    cpuHigh: "󰡳",
    memory: "",
    chip: "",
    eyeOpen: "",
    eyeClosed: "",
    bell: "",
    bellMuted: "",
    markRead: "",
    markUnread: "",
    networkConnected: "󰱔",
    networkDisconnected: "⚠",
    networkUnavailable: "󰲛",
    ethernet: "󰈀",
    wifiStrengthOutline: "󰤯",
    wifiStrength1: "󰤟",
    wifiStrength2: "󰤢",
    wifiStrength3: "󰤥",
    wifiStrength4: "󰤨",
    chevronLeft: "",
    chevronRight: "",
    upload: "",
    download: "",
    temperatureEmpty: "",
    temperatureHalf: "",
    temperatureFull: "",
    volumeOff: "",
    volumeLow: "",
    volumeMedium: "",
    volumeHigh: "",
    volumeMuted: "",
    microphone: "",
    microphoneMuted: ""
}

function glyph(name) {
    return glyphs[name] || ""
}
