.pragma library

const glyphs = {
    browser: "",
    terminal: "",
    code: "",
    music: "",
    window: "",
    workspaceDefault: "",
    warning: "",
    batteryCharging: "",
    batteryPlugged: "",
    batteryEmpty: "",
    batteryQuarter: "",
    batteryHalf: "",
    batteryThreeQuarters: "",
    batteryFull: "",
    brightnessMinimum: "",
    brightnessLow: "",
    brightnessLowerMiddle: "",
    brightnessMiddle: "",
    brightnessUpperMiddle: "",
    brightnessHigh: "",
    brightnessHigher: "",
    brightnessNearMaximum: "",
    brightnessMaximum: "",
    cpu: "",
    memory: "",
    eyeOpen: "",
    eyeClosed: "",
    bell: "",
    bellMuted: "",
    markRead: "",
    markUnread: "",
    networkConnected: "󰱔",
    networkDisconnected: "⚠",
    chevronLeft: "",
    chevronRight: "",
    upload: "",
    download: "",
    temperatureCool: "",
    temperatureWarm: "",
    temperatureHot: "",
    temperatureCritical: "",
    volumeOff: "",
    volumeLow: "",
    volumeHigh: "",
    volumeMuted: "",
    microphone: "",
    microphoneMuted: ""
}

function glyph(name) {
    return glyphs[name] || ""
}
