templates:
  params:
    author-email: <author@email.com>
    copyright: 2018 Christopher Reichert
    github-username: creichert
    author-name: Christopher Reichert
ghc-options:
  $locals: -j
system-ghc: true
